Clean script

diff --git a/dmg2dir b/dmg2dir
--- a/dmg2dir
+++ b/dmg2dir
@@ -3,7 +3,7 @@
 #################################################################################################
 #					ENVIRONMENT						#
 #################################################################################################
-[[ $DEBUG != 0 ]] && set -x
+[[ -n $DEBUG ]] && [[ $DEBUG != 0 ]] && set -x
 
 export TEXTDOMAINDIR=@TEXTDOMAINDIR@
 export TEXTDOMAIN=dmg2dir
@@ -12,6 +12,7 @@ geniso=$(command -v genisoimage)
 darling=$(command -v dyld)
 version="3.0.3"
 critical=0
+fail=false
 
 name=			# -n
 savepath=		# -p
@@ -31,48 +32,66 @@ overwriteiso=false	# --overwrite-iso
 #					COMMONS	FUNCTIONS					#
 #################################################################################################
 msg() {
+	local str="$1"
+
 	if ! [[ -n "$quiet" ]]; then
-		str=$1
 		shift
-		printf "\033[1;32m==>\033[0;1m `gettext -s "$str"` \033[0m\n" "$@"
+		printf "\033[1;32m==>\033[0;1m $(gettext -s "$str")\033[0m\n" "$@"
 	fi
 }
 
 msgverbose1() {
+	local str="$1"
+
 	if [[ -n "$verbose1" ]]; then
-		str=$1
 		shift
-		printf "\033[1;34m  ->\033[0m `gettext -s "$str"` \n" "$@"
+		printf "\033[1;34m  ->\033[0m $(gettext -s "$str")\n" "$@"
 	fi
 }
 
 msgverbose2() {
+	local str="$1"
+
 	if [[ -n "$verbose2" ]]; then
-		echo -e "    $1"
+		shift
+		printf "    $(gettext -s "$str")\n" "$@"
 	fi
 }
 
-error() {
-	if [[ -z $err ]]; then
-		err=$2
-		echo -e "`gettext -s "$1"`"
+msgwarning() {
+	local str="$1"
 
-		if [[ -n "$verbose1" ]]; then
-			printf "\033[1;31m `gettext -s 'Error %s has occurred.'` \033[0m\n" "$2"
-		fi
+	shift
+	printf "\033[1;33m$(gettext -s "$str")\033[0m\n" "$@"
+}
+
+msgerror() {
+	local error="$1"
+	local str="$2"
+
+	if ! $fail; then
+		fail=true
+		shift
+		shift
+
+		local errorstr=`printf "$(gettext -s "$str")\n" "$@"`
+		printf "\033[1;31m$(gettext -s 'Error %s: %s')\033[0m\n" "$error" "$errorstr"
+
+		# Clean
+		$iso && rm -rf $verbose1 "$vtree"
 
 		if [[ $critical == 2 ]] ; then
 			for part in ${loop}p*; do
-				$udiskcmd unmount --no-user-interaction --block-device $part 2>&1 /dev/null
+				umountpart $part
 			done
 		fi
 
 		if [[ $critical > 0 ]] ; then
-			$udiskcmd loop-delete --no-user-interaction --block-device $loop 2>&1 /dev/null
+			delloop
 		fi
 	fi
 
-	exit $err
+	exit $error
 }
 
 usage() {
@@ -110,36 +129,45 @@ checkdep() {
 	local code="$3"
 
 	if [[ -z "$command" ]]; then
-		error "Dependency $depname is required." $code
+		msgerror "$code" "Dependency %s is required." "$depname"
 	fi
 }
 
 checkfile() {
-	if [[ ! -f $1 ]]; then
-		error "No output file found." $2
+	local file="$1"
+	local code="$2"
+
+	if [[ ! -f "$file" ]]; then
+		msgerror "$code" "File %s doesn't exist." "$file"
 	fi
 }
 
 checkvar() {
-	if [[ -z $1 ]]; then
-		error "Variable is empty." $2
+	local var="$1"
+	local code="$2"
+
+	if [[ -z "$var" ]]; then
+		msgerror "$code" "Variable is empty."
 	fi
 }
 
 checkdir() {
-	if [[ ! -d $1 ]]; then
-		error "Directory not fount." $2
-	fi
+	local directory="$1"
+	local code="$2"
 
-	if [[ $3 == 2 ]]; then
-		[[ -z "$(ls -A $1)" ]] && \
-		error "Directory is empty." $2
+	if [[ ! -d "$directory" ]]; then
+		msgerror "$code" "Directory %s doesn't exist." "$directory"
+	elif [[ -z "$(ls -A $directory)" ]]; then
+		msgerror "$code" "Directory %s is empty." "$directory"
 	fi
 }
 
-checkcode() {
-	if [[ $1 != 0 ]]; then
-		error "Command fails." $2
+checkret() {
+	local ret="$1"
+	local code="$2"
+
+	if [[ $ret != 0 ]]; then
+		msgerror "$code" "Command fails."
 	fi
 }
 
@@ -148,19 +176,20 @@ checkcode() {
 #					MAIN FUNCTIONS						#
 #################################################################################################
 convertdmg() {
-	msgverbose1 "Convert %s to %s" "$filetoconvert" "$tmpdir/$name.img"
+	msgverbose1 "Converting %s to %s" "$filetoconvert" "$tmpdir/$name.img"
 	dmg2img $quiet $verbose1 $verbose2 -i "$filetoconvert" -o "$tmpdir/$name.img"
-	checkfile "$tmpdir/$name.img" 10
+	checkret "$?" 10
+	checkfile "$tmpdir/$name.img" 11
 }
 
 addloop() {
-	msgverbose1 "Set up loop-device"
+	msgverbose1 "Setting up loop-device for file %s" "$tmpdir/$name.img"
 	loop=$($udiskcmd loop-setup --no-user-interaction --read-only --file "$tmpdir/$name.img")
 	checkvar "$loop" 20
 	msgverbose2 "$loop"
 	critical=1
 
-	msgverbose1 "Retrieve loop device name"
+	msgverbose1 "Retrieving loop device name"
 	loop=${loop%.}
 	loop=${loop#*/dev/loop}
 	checkvar "$loop" 21
@@ -173,7 +202,7 @@ mountpart() {
 
 	mountpoint=$(findmnt --noheadings --output TARGET $part)
 	if [[ -z "$mountpoint" ]]; then
-		msgverbose1 "Mount loop-device partition %s" "$part"
+		msgverbose1 "Mounting loop-device partition %s" "$part"
 		$udiskcmd mount --block-device $part > $output
 		mountpoint=$(findmnt --noheadings --output TARGET $part)
 	fi
@@ -183,42 +212,45 @@ mountpart() {
 
 	if $iso; then
 		local label=$(basename "$mountpoint")
+		msgverbose1 "Creating virtual tree %s" "$tmpdir/$name/$label"
 		ln -sf $verbose1 "$mountpoint" "$tmpdir/$name/$label"
 	fi
 }
 
 copydir() {
-	msgverbose1 "Copy files in application directory"
-	cp -Raup $verbose1 "$mountpoint" "$appdir"
-	checkdir "$appdir" 40 2
+	msgverbose1 "Copying files from %s to application directory" "$mountpoint"
+	cp -Rau $verbose1 "$mountpoint" "$appdir"
+	checkdir "$appdir" 40
 }
 
 convertiso() {
-	$geniso $verbose1 -V "$name" -iso-level 3 -UDF -R -probe -g -posix-L -o "$appdir.iso" "$vtree"
+	[[ -n "$quiet" ]] && local genisoquiet="-quiet"
+
+	msgverbose1 "Generating ISO file from virtual tree %s" "$vtree"
+	$geniso $genisoquiet $verbose1 -V "$name" -iso-level 3 -UDF -R -probe -g -posix-L -o "$appdir.iso" "$vtree"
 	checkfile "$appdir.iso" 50
 }
 
 umountpart() {
 	local part=$1
 
-	msgverbose1 "Unmount loop-device partition %s" "$part"
+	msgverbose1 "Unmounting loop-device partition %s" "$part"
 	$udiskcmd unmount --no-user-interaction --force --block-device $part > $output
-	checkcode "$?" 60
-	msgverbose2 "Device unmounted"
+	checkret "$?" 60
 	critical=1
 }
 
 delloop() {
 	if [[ -f $loop* ]]; then
-		msgverbose1 "Delete loop-device"
-		$udiskcmd loop-delete --no-user-interaction --block-device $loop
-		checkcode "$?" 70
-		msgverbose2 "Device deleted"
+		msgverbose1 "Deleting loop-device %s" "$loop"
+		$udiskcmd loop-delete --no-user-interaction --block-device $loop > $output
+		checkret "$?" 70
 	fi
 	critical=0
 }
 
 launcher() {
+	msgverbose1 "Searching for executable in application directory"
 	find "$appdir"/*/*.app/Contents/MacOS -exec file '{}' \; | grep "Mach-O" | grep "executable" | cut -f1 -d: | while IFS= read -r executable; do
 		msgverbose1 "Found file %s, launch it with dyld" "$executable"
 		dyld "$executable"
@@ -232,11 +264,11 @@ launcher() {
 # Args
 OPTS=`getopt -o n:p:t:ridqvwVh --long name:,path:,tmp:,run,iso,iso-only,quiet,verbose,version,help,overwrite-img,overwrite-dir,overwrite-iso -n 'dmg2dir' -- "$@"`
 if [[ $? != 0 ]]; then
-	error "Failed parsing options." 1
+	msgerror 1 "Failed parsing options."
 fi
 
 eval set -- "$OPTS"
-while true ; do
+while true; do
 	case "$1" in
 		-n|--name)		shift; name="$1";;
 		-p|--path)		shift; savepath="$1";;
@@ -252,26 +284,25 @@ while true ; do
 		--overwrite-dir)	overwritedir=true;;
 		--overwrite-iso)	overwriteiso=true;;
 		--)			shift; break;;
-		*)			 echo "Internal error!"; exit 1;;
+		*)			echo "Internal error!"; exit 1;;
 	esac
 	shift
 done
 
 # Prerequisites
-msg "Check prerequisites..."
+msg "Checking prerequisites..."
 filetoconvert="$1"
 if [[ -z "$filetoconvert" ]]; then
 	usage
 	exit 1
 fi
 if [[ ! -f "$filetoconvert" ]]; then
-	error "File doesn't exist." 1
+	msgerror 2 "File %s doesn't exist." "$filetoconvert"
 fi
 checkdep "$udiskcmd" "udisks2" 1
-#if ! $(groups | grep -q disk); then
-#	error "You need to be in group 'disk'."
-#fi
 
+# Variables
+msg "Setting variables..."
 [[ -z "$name" ]] && name=$(basename "$filetoconvert" .dmg)
 [[ -z "$savepath" ]] && savepath=$(dirname "$filetoconvert")
 [[ -z "$verbose2" ]] && output="/dev/null" || output="/dev/stdout"
@@ -279,55 +310,58 @@ appdir="$savepath/$name"
 vtree="$tmpdir/$name"
 
 if ! $noappdir && ! $overwritedir && [[ -e "$appdir" ]]; then
-	error "Directory $appdir already exists. Use --overwrite-dir to overwrite it." 1
+	msgerror 3 "Directory %s already exists. Use --overwrite-dir to overwrite it." "$appdir"
 fi
 if $iso && ! $overwriteiso && [[ -e "$appdir.iso" ]]; then
-	error "File $appdir.iso already exists. Use --overwrite-iso to overwrite it." 1
+	msgerror 4 "File %s already exists. Use --overwrite-iso to overwrite it." "$appdir.iso"
 fi
 
-# Start
-if [[ ! -d "$tmpdir" ]] || [[ ! -d "$tmpdir/$name" ]] ; then
-	msg "Make temporary working directory..."
-	mkdir -p $verbose1 "$tmpdir"
-fi
+# Temporary directories
+msg "Making temporary working directories..."
+mkdir -p $verbose1 "$tmpdir"
 $iso && mkdir -p $verbose1 "$vtree"
 
-msg "Convert DMG file to IMG file..."
+# Conversion
+msg "Converting DMG file to an IMG file..."
 if [[ ! -f "$tmpdir/$name.img" ]] || $overwriteimg; then
 	convertdmg
 else
-	msgverbose1 "File %s already exists. Skipping conversion. Use --overwrite-img to overwrite it." "$tmpdir/$name.img"
+	msgwarning "File %s already exists. Skipping conversion. Use --overwrite-img to overwrite it." "$tmpdir/$name.img"
 fi
 
-msg "Prepare loop device..."
+# Mount
+msg "Setting loop device..."
 addloop
-
-if ! $noappdir; then
-	msgverbose1 "Make application directory: %s" "$appdir"
-	mkdir -p $verbose1 "$appdir"
-fi
-
 for part in ${loop}p*; do
 	mountpart $part
-	if ! $noappdir; then
-		copydir
-	fi
 done
 
-if $iso; then
-	msg "Generate ISO file..."
-	convertiso
-	rm -rf $verbose1 "$vtree"
+# Extraction (directory)
+if ! $noappdir; then
+	msg "Extracting files to %s..." "$appdir"
+	mkdir -p $verbose1 "$appdir"
+	for part in ${loop}p*; do
+		copydir
+	done
 fi
 
+# Extraction (ISO)
+if $iso; then
+	msg "Creating ISO file %s..." "$appdir.iso"
+	convertiso
+fi
+
+# Clean
+msg "Cleaning..."
+$iso && rm -rf $verbose1 "$vtree"
 for part in ${loop}p*; do
 	umountpart $part
 done
-
 delloop
 
+# Run
 if $run && ! $noappdir; then
-	msg "Try to run binary file with Darling..."
+	msg "Trying to run extracted application with Darling..."
 	launcher
 fi
 
